version: '3'
services:
  server:
    build: .
    environment:
      - "GATEKEEPER_CONSOLE=0"
      - "GATEKEEPER_DB_BACKEND=postgres"
      - "GATEKEEPER_DB_CONNECTION_STRING=postgres://gatekeeper:gatekeeper@db/gatekeeper"
    volumes:
      - .:/go/src/app
    depends_on:
      - db
  db:
    image: "postgres:10.1-alpine"
    environment:
      - "POSTGRES_PASSWORD=gatekeeper"
      - "POSTGRES_USER=gatekeeper"
      - "POSTGRES_DB=gatekeeper"
  web:
    build: scripts/nginx-docker
    ports:
      - "8080:80"
    depends_on:
      - server
